/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api": {
    get: operations["getHealth"];
  };
  "/api/auth/signup": {
    /**
     * Register a new user
     * @description Creates a new user account and returns user data with authentication tokens
     */
    post: operations["signUp"];
  };
  "/api/auth/login": {
    /**
     * Login user
     * @description Authenticates a user and returns user data with authentication tokens
     */
    post: operations["login"];
  };
  "/api/auth/forgot-password": {
    /**
     * Request password reset
     * @description Sends a password reset email to the user
     */
    post: operations["forgotPassword"];
  };
  "/api/auth/reset-password": {
    /**
     * Reset password
     * @description Resets user password using the token received via email
     */
    post: operations["resetPassword"];
  };
  "/api/auth/current-user": {
    /**
     * Get current user
     * @description Returns the authenticated user's data. Requires JWT token in Authorization header.
     */
    get: operations["getCurrentUser"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SignupDto: {
      /**
       * @description User's full name
       * @example John Doe
       */
      fullName: string;
      /**
       * @description User's email address
       * @example john.doe@example.com
       */
      email: string;
      /**
       * @description User's password (minimum 8 characters)
       * @example SecurePassword123!
       */
      password: string;
    };
    UserDataDto: {
      /**
       * @description User's unique identifier
       * @example 507f1f77bcf86cd799439011
       */
      id: string;
      /**
       * @description User's full name
       * @example John Doe
       */
      fullName: string;
      /**
       * @description User's email address
       * @example john.doe@example.com
       */
      email: string;
      /**
       * @description Whether the user's email has been verified
       * @example false
       */
      emailVerified: boolean;
    };
    TokenDto: {
      /**
       * @description JWT access token
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
       */
      accessToken: string;
      /**
       * @description JWT refresh token
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
       */
      refreshToken: string;
    };
    LoggedInUserDto: {
      user: components["schemas"]["UserDataDto"];
      tokens: components["schemas"]["TokenDto"];
    };
    LoginDto: {
      /**
       * @description User's email address
       * @example john.doe@example.com
       */
      email: string;
      /**
       * @description User's password
       * @example SecurePassword123!
       */
      password: string;
    };
    ForgotPasswordDto: {
      /**
       * @description User's email address to send password reset link
       * @example john.doe@example.com
       */
      email: string;
    };
    APIResponseDto: {
      /**
       * @description Response message
       * @example Password reset email sent successfully
       */
      message: string;
    };
    ResetPasswordDto: {
      /**
       * @description Password reset token received via email
       * @example abc123def456ghi789
       */
      token: string;
      /**
       * @description New password (minimum 8 characters)
       * @example NewSecurePassword123!
       */
      newPassword: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  getHealth: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  /**
   * Register a new user
   * @description Creates a new user account and returns user data with authentication tokens
   */
  signUp: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignupDto"];
      };
    };
    responses: {
      /** @description User successfully registered */
      201: {
        content: {
          "application/json": components["schemas"]["LoggedInUserDto"];
        };
      };
      /** @description Email already exists */
      409: {
        content: never;
      };
    };
  };
  /**
   * Login user
   * @description Authenticates a user and returns user data with authentication tokens
   */
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      /** @description User successfully logged in */
      200: {
        content: {
          "application/json": components["schemas"]["LoggedInUserDto"];
        };
      };
      /** @description Invalid credentials */
      401: {
        content: never;
      };
    };
  };
  /**
   * Request password reset
   * @description Sends a password reset email to the user
   */
  forgotPassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordDto"];
      };
    };
    responses: {
      /** @description Password reset email sent successfully */
      200: {
        content: {
          "application/json": components["schemas"]["APIResponseDto"];
        };
      };
      /** @description User not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Reset password
   * @description Resets user password using the token received via email
   */
  resetPassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordDto"];
      };
    };
    responses: {
      /** @description Password reset successfully */
      200: {
        content: {
          "application/json": components["schemas"]["APIResponseDto"];
        };
      };
      /** @description Invalid or expired token */
      400: {
        content: never;
      };
    };
  };
  /**
   * Get current user
   * @description Returns the authenticated user's data. Requires JWT token in Authorization header.
   */
  getCurrentUser: {
    responses: {
      /** @description Current user data */
      200: {
        content: {
          "application/json": components["schemas"]["UserDataDto"];
        };
      };
      /** @description Unauthorized - Invalid or missing token */
      401: {
        content: never;
      };
    };
  };
}
